### ISSUE TITLE
Issue with using custom ARM template file names

### ISSUE THREAD

**Issue by JFolberth** [sam-cogan/arm-ttk-extension#13]
If using a ARM file with a different name then what is defined as IsMainTemplate :
'mainTemplate.json', 'azureDeploy.json', 'prereq.azuredeploy.json' 

The TTK extension is giving an incorrect error message
`The location parameter of nested templates must not have a defaultValue property. It is "[resourceGroup().location]"`

One might want to use custom names for their ARM templates if dealing with deploying multiple templates in the same release to make it easier to deploy using YAML pipelines

For instance if structuring a project with at least two arm templates: One for an App Service Plan and one for each function app or app service to keep things better organized arm template deploy files might be named appserviceplan.deploy.json, appservice1.deploy.json, etc... If passing these files into the ttk the location ID will fail these would not be recognized as a "MainTemplate" and fail this if block:
```
if ($IsMainTemplate){ 
    if($locationParameter.defaultValue -and "$($locationParameter.defaultvalue)".Trim() -ne '[resourceGroup().location]') {
    Write-Error "The defaultValue of the location parameter in the main template must not be a specific location. The default value must be [resourceGroup().location]. It is `"$($locationParameter.defaultValue)`"" -ErrorId Location.Parameter.Hardcoded -TargetObject $parameter
}
# In all other templates:
# if the parameter named "location" exists, it must not have a defaultValue property
# Note that Powershell will count an empty string (which should fail the test) as null if not explictly tested, so we check for it
}else {
    if($locationParameter.defaultValue -ne $null){ 
        Write-Error "The location parameter of nested templates must not have a defaultValue property. It is `"$($locationParameter.defaultValue)`"" -ErrorId Location.Parameter.DefaultValuePresent -TargetObject $parameter
    }   
}
```

**Comment by sam-cogan** [comment]
Can you provide a scene shot of your extension settings please? The extension is designed to work with arm templates named whatever you like, as I do test for that, so I need to figure out he scenario where it's not working for you. 
Thanks.

**Comment by JFolberth** [comment]
Sure.  I am using YAML pipelines and trying to run the ttk against a series of arm templates in my pipeline.  Here is the yaml:
```
jobs:
- job : RunARMTTK
  steps:
  - task: RunARMTTKTests@1
    inputs:
        templatelocation: '$(System.DefaultWorkingDirectory)\Infrastructure\*.json'
        resultLocation: '$(System.DefaultWorkingDirectory)\Infrastructure'
  - task: PublishTestResults@2
    inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)\Infrastructure\*-armttk.xml'
    condition: always()
```
