### ISSUE TITLE
##[error]Failures found in test results

### ISSUE THREAD

**Issue by maikvandergaag** [sam-cogan/arm-ttk-extension#15]
This weekend the version of the ARM-TTK extension was updated. Since then our build are failing with the message: ##[error]Failures found in test results.

I would expect that the extension continues and that the failures will be published. But the build ends. We are using YAML pipelines:

- task: RunARMTTKTests@1
  displayName: 'Validate - ARM Templates'
  inputs:
    templatelocation: '$(Build.Repository.LocalPath)\src\arm-templates'
    resultLocation: '$(Build.Repository.LocalPath)'
    skipTests: 'ID''s are derived from resource ID''s'

**Comment by sam-cogan** [comment]
Hi, the extension is designed to fail if any of the tests fail, so you can fail your build when tests fail. This has always been the case, but the test you mention was added in the new version I believe, so this may have been the first time you saw a failure. 

To ensure your tests are always published even if it fails you need to set your test publish to always run. You can see an example of this in the readme. 

```
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
  condition: always()
```
