### ISSUE TITLE
Passing a single directory for `templateLocation` runs tests on files in nested directories

### ISSUE THREAD

**Issue by erik-source** [sam-cogan/arm-ttk-extension#58]
When running tests with a directory specified for `templateLocation`, the extension seems to be picking up non-template json files that live in nested directories. I haven't dug into the source here, so this may be intentional or we may have misconfigured the extension. I wouldn't expect recursion unless specifying `**`. Would love to know if we're doing something wrong here!

We have ADF json files in directories alongside our main template so the structure looks like this:
```
$(System.DefaultWorkingDirectory)\AzureResourceGroup
├- azuredeploy.json
├- azuredeploy.parameters.<env>.json
├- dataset
|   └- myDataset.json
└- linkedService
    └- myLinkedService.json
```

We are passing these inputs to the task:
```yaml
- task: RunARMTTKTests@1
  displayName: 'Run ARM TTK Tests'
  inputs:
    templatelocation: $(System.DefaultWorkingDirectory)\AzureResourceGroup\*
    resultLocation: $(System.DefaultWorkingDirectory)\TestResults
    mainTemplates: azuredeploy.json
    cliOutputResults: true
```

I would expect that since we've passed a directory with a single-level wildcard, that only the files directory in that directory would be tested. When run, every `json` file is tested no matter what level. We have tried removing the `*` and just passing the directory name itself but this yields the same results. We have also tried various combinations of `mainTemplates` and wildcard/directory/file for `templateLocation` without success. The only case we've been able to get working is specifying `azuredeploy.json` for `templateLocation` an nothing else.

Until today this has been fine, as all of the ADF files pass validation. For whatever reason today, a new dataset started causing the most bizarre test failures, such as "VM size must be a parameter" and "DependsOn best practices". Obviously an ADF dataset contains no VMs (nor does any template in this repo) so these failures make no sense.
