### ISSUE TITLE
Update ARM-TTK

### ISSUE THREAD

**Issue by anand-raju** [sam-cogan/arm-ttk-extension#62]
The latest version of ARM-TTK supports comments in ARM templates whereas the ARM-TTK extension does not.

When running the extension, the error is:
```ps
"Microsoft.PowerShell.Commands.WriteErrorException: Could not import 'C:__w\1\s\src\deploy\templates\mainTemplate.json' in template file mainTemplate.json"
```

Stack Trace:
```ps
at &lt;ScriptBlock&gt;, C:\__w\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.5.1\arm-ttk\testcases\AllFiles\JSONFiles-Should-Be-Valid.test.ps1: line 16
at Test-Case, C:\__w\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.5.1\arm-ttk\Test-AzTemplate.ps1: line 249
at Test-Group, C:\__w\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.5.1\arm-ttk\Test-AzTemplate.ps1: line 313
at Test-FileList, C:\__w\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.5.1\arm-ttk\Test-AzTemplate.ps1: line 553
at Test-AzTemplate&lt;End&gt;, C:\__w\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.5.1\arm-ttk\Test-AzTemplate.ps1: line 699
at Test-FolderContents, C:\__w\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.5.1\invoke-ttk.psm1: line 14
at Invoke-TTK, C:\__w\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.5.1\invoke-ttk.psm1: line 120
at &lt;ScriptBlock&gt;, C:\__w\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.5.1\powershell.ps1: line 40
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 1
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 22
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 18
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 1
```

Here's how ARM-TTK extension is invoked in the pipeline:

```yaml
- stage: test
      jobs:
      - job: test_arm
        pool:
          type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/job

        steps:
          - task: RunARMTTKTests@1
            continueOnError: true
            inputs:
              templatelocation: '$(Build.SourcesDirectory)/src/deploy/templates'
              resultLocation: '$(Build.SourcesDirectory)/out/TestResults'
              allTemplatesMain: true

          - task: PublishTestResults@2
            condition: always()
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: '$(Build.SourcesDirectory)/out/TestResults/*-armttk.xml'
```

When running locally

```ps
Test-AzTemplate -MainTemplateFile .\src\deploy\Templates\mainTemplate.json
```

Runs successfully.
